--- 
language: php

php:
  - 5.3

script:
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - composer require satooshi/php-coveralls:0.6.*
  - composer install --dev
  - mysql -e 'create database `test-jam-monetary`;'
  - mysql test-jam-monetary < tests/test_data/structure.sql

after_script:
  - php vendor/bin/coveralls -v
